name: landolupusweb
recipe: laravel
config:
  php: '8.1'
  composer_version: '2.3.7'
  webroot: public
  database: mariadb:10.6.8
  via: nginx
  xdebug: "develop,debug"
services:
  appserver:
    build:
      - composer i
  database:
    portforward: 3307
  node:
    type: compose
    services:
      image: node:16.15.1
      command: tail -f /dev/null
      ports:
        - "3000:3000"
    scanner: false
    portforward: 3000
  cache:
    type: compose
    app_mount: false
    services:
      image: redis:6.2.7-alpine
      command: docker-entrypoint.sh redis-server
tooling:
  npm:
    service: node
  npx:
    service: node
  ide-helper:
    service: appserver
    description: Generate IDE helper files
    cmd:
      - php artisan ide-helper:generate
      - php artisan ide-helper:meta
      - php artisan ide-helper:models -N -p
  update-deps:
    description: Update all dependencies of the project
    cmd:
      - appserver: composer update
      - node: npm update -D
  install-deps:
    description: Install command for all dependencies
    cmd:
      - appserver: composer i
      - node: npm i
  mix:
    service: node
    description: Run mix inside node container
    cmd: npx mix
  test:
    service: appserver
    description: Launch test suite and PhpStan
    cmd:
      - php artisan test -p
      - ./vendor/bin/phpstan
  coverage:
    service: appserver
    description: Launch test suite with coverage enabled
    cmd: php artisan test -p --coverage
    env:
      XDEBUG_MODE: coverage

