name: landolupusweb
recipe: laravel
config:
  php: '8.0'
  webroot: public
  database: mariadb:10.5
  xdebug: true
  password: postgres
services:
  database:
    portforward: 3307
  node:
    type: node:16
    globals:
      npm: 8
tooling:
  npm:
    service: node
  npx:
    service: node
  ide-helper:
    service: appserver
    description: Generate IDE helper files
    cmd:
      - php artisan ide-helper:generate
      - php artisan ide-helper:meta
      - php artisan ide-helper:models -N -p
  update-deps:
    description: Update all dependencies of the project
    cmd:
      - appserver: composer update
      - node: npm update -D
  mix:
    service: node
    description: Run mix inside node container
    cmd: npx mix
  test:
    service: appserver
    description: Launch test suite and PhpStan
    cmd:
      - php artisan test -p
      - ./vendor/bin/phpstan
  coverage:
    service: appserver
    description: Launch test suite with coverage enabled
    cmd: php artisan test -p --coverage
    env:
      XDEBUG_MODE: coverage

