version: '3.8'

services:
    web:
        image: tbaile/lupus-web:latest
        build:
            dockerfile: docker/nginx/Dockerfile
            context: .
        restart: unless-stopped
        depends_on:
            - app
        ports:
            -   "80:80"
        env_file:
            - .env.compose
        volumes:
            - public:/var/www/html/public:ro
            - storage:/var/www/html/storage

    app:
        image: tbaile/lupus-app:latest
        build:
            dockerfile: docker/php/Dockerfile
            context: .
        restart: unless-stopped
        depends_on:
            - database
            - redis
        volumes:
            - public:/app/public
            - storage:/var/www/html/storage
        env_file:
            - .env.compose

    scheduler:
        image: tbaile/lupus-app:latest
        build:
            dockerfile: docker/php/Dockerfile
            context: .
        restart: unless-stopped
        depends_on:
            - database
            - redis
        volumes:
            - storage:/var/www/html/storage
        env_file:
            - .env.compose
        command: [ "scheduler" ]
    queue:
        image: tbaile/lupus-app:latest
        build:
            dockerfile: docker/php/Dockerfile
            context: .
        restart: unless-stopped
        depends_on:
            - database
            - redis
        volumes:
            - storage:/var/www/html/storage
        env_file:
            - .env.compose
        command: [ "queue" ]
    database:
        image: mariadb:10.6
        restart: unless-stopped
        volumes:
            - database:/var/lib/mysql
        env_file:
            - .env.compose
    redis:
        image: redis
        restart: unless-stopped

volumes:
    storage:
    public:
    database:
