version: '3.4'

services:
    web:
        image: tbaile/lupus-web:latest
        restart: unless-stopped
        depends_on:
            - app
        volumes:
            - public:/var/www/html/public:ro
            - storage:/var/www/html/storage
        environment:
            APP_DOMAIN: "${APP_DOMAIN}"
        healthcheck:
            test: ["CMD", "curl", "--fail", "--silent", "--output", "/dev/null", "http://localhost"]
            start_period: 10s
    app:
        image: tbaile/lupus-app:latest
        restart: unless-stopped
        depends_on:
            - database
        env_file:
            - .env
        volumes:
            - public:/app/public
            - storage:/var/www/html/storage
        healthcheck:
            test: [ "CMD", "php-fpm-healthcheck" ]
            start_period: 10s
    scheduler:
        image: tbaile/lupus-app:latest
        restart: unless-stopped
        depends_on:
            - database
        env_file:
            - .env
        volumes:
            - storage:/var/www/html/storage
        healthcheck:
            test: [ "CMD-SHELL", "ps -ef | grep php | grep -v grep" ]
            start_period: 10s
        command: [ "scheduler" ]
    queue:
        image: tbaile/lupus-app:latest
        restart: unless-stopped
        depends_on:
            - database
        env_file:
            - .env
        volumes:
            - storage:/var/www/html/storage
        healthcheck:
            test: [ "CMD-SHELL", "ps -ef | grep php | grep -v grep" ]
            start_period: 10s
        command: [ "queue" ]
    database:
        image: mariadb:10
        restart: unless-stopped
        environment:
            MARIADB_RANDOM_ROOT_PASSWORD: "true"
            MARIADB_DATABASE: "${DB_DATABASE}"
            MARIADB_USER: "${DB_USERNAME}"
            MARIADB_PASSWORD: "${DB_PASSWORD}"
        volumes:
            - database:/var/lib/mysql
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U postgres" ]
            start_period: 10s

volumes:
    storage:
    public:
    database:
