name: lupus-deployment
services:
    redis:
        image: redis:6.2.7-alpine
        healthcheck:
            test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
        volumes:
            - redis:/data
    pgsql:
        image: postgres:14.6-alpine
        healthcheck:
            test: ["CMD", "pg_isready", "-q", "-d", "lupusapi", "-U", "lupusapi"]
        volumes:
            - pgsql:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: 'lupusapi'
            POSTGRES_USER: 'lupusapi'
            POSTGRES_PASSWORD: 'lupusapi'
    setup:
        image: tbaile/lupus-api-app:develop
        depends_on:
            - pgsql
            - redis
        volumes:
            - public:/app/public
            - bootstrap:/var/www/html/bootstrap
            - storage:/var/www/html/storage
        secrets:
            -   source: env_file
                target: /var/www/html/.env
        environment:
            ROLE: "setup"
    app:
        image: tbaile/lupus-api-app:develop
        healthcheck:
            test: [ "CMD", "php-fpm-healthcheck" ]
        depends_on:
            setup:
                condition: service_completed_successfully
        volumes:
            - public:/app/public
            - bootstrap:/var/www/html/bootstrap
            - storage:/var/www/html/storage
        secrets:
            -   source: env_file
                target: /var/www/html/.env
    scheduler:
        image: tbaile/lupus-api-app:develop
        depends_on:
            setup:
                condition: service_completed_successfully
        stop_signal: SIGKILL
        volumes:
            - bootstrap:/var/www/html/bootstrap
            - storage:/var/www/html/storage
        secrets:
            -   source: env_file
                target: /var/www/html/.env
        environment:
            ROLE: "scheduler"
    queue:
        image: tbaile/lupus-api-app:develop
        depends_on:
            setup:
                condition: service_completed_successfully
        stop_signal: SIGKILL
        volumes:
            - bootstrap:/var/www/html/bootstrap
            - storage:/var/www/html/storage
        secrets:
            -   source: env_file
                target: /var/www/html/.env
        environment:
            ROLE: "queue"
    web:
        image: tbaile/lupus-api-web:develop
        healthcheck:
            test: [ "CMD", "curl", "--fail", "--silent", "--output", "/dev/null", "http://localhost" ]
        depends_on:
            - app
        ports:
            - "8888:80"
        volumes:
            - public:/var/www/html/public:ro
        environment:
            FPM_HOST: app

volumes:
    redis: {}
    pgsql: {}
    public: {}
    bootstrap: {}
    storage: {}

secrets:
    env_file:
        file: .env
