name: lupus-deployment
services:
    redis:
        image: redis:6.2.7-alpine
        healthcheck:
            test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
        volumes:
            - redis:/data
    database:
        image: mariadb:10.6.10
        healthcheck:
            test: [ "CMD", "mysql", "-ulupusapi", "-plupusapi", "-e", "SELECT 1" ]
        volumes:
            - database:/var/lib/mysql
        environment:
            MYSQL_RANDOM_ROOT_PASSWORD: true
            MYSQL_DATABASE: lupusapi
            MYSQL_USER: lupusapi
            MYSQL_PASSWORD: lupusapi
    setup:
        image: tbaile/lupus-api-app:develop
        depends_on:
            - database
            - redis
        volumes:
            - public:/app/public
            - bootstrap:/var/www/html/bootstrap
            - storage:/var/www/html/storage
        secrets:
            -   source: env_file
                target: /var/www/html/.env
        environment:
            ROLE: "setup"
    app:
        image: tbaile/lupus-api-app:develop
        healthcheck:
            test: [ "CMD", "php-fpm-healthcheck" ]
        depends_on:
            setup:
                condition: service_completed_successfully
        networks:
            default:
                aliases:
                    - app
        volumes:
            - public:/app/public
            - bootstrap:/var/www/html/bootstrap
            - storage:/var/www/html/storage
        secrets:
            -   source: env_file
                target: /var/www/html/.env
    scheduler:
        image: tbaile/lupus-api-app:develop
        depends_on:
            setup:
                condition: service_completed_successfully
        stop_signal: SIGKILL
        volumes:
            - bootstrap:/var/www/html/bootstrap
            - storage:/var/www/html/storage
        secrets:
            -   source: env_file
                target: /var/www/html/.env
        environment:
            ROLE: "scheduler"
    queue:
        image: tbaile/lupus-api-app:develop
        depends_on:
            setup:
                condition: service_completed_successfully
        stop_signal: SIGKILL
        volumes:
            - bootstrap:/var/www/html/bootstrap
            - storage:/var/www/html/storage
        secrets:
            -   source: env_file
                target: /var/www/html/.env
        environment:
            ROLE: "queue"
    web:
        image: tbaile/lupus-api-web:develop
        healthcheck:
            test: [ "CMD", "curl", "--fail", "--silent", "--output", "/dev/null", "http://localhost" ]
        depends_on:
            - app
        ports:
            - "80:80"
        volumes:
            - public:/var/www/html/public:ro
        environment:
            FPM_HOST: app

volumes:
    redis: {}
    database: {}
    public: {}
    bootstrap: {}
    storage: {}

secrets:
    env_file:
        file: .env
