name: Build
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_call:
    secrets:
      registry_username:
        required: true
      registry_password:
        required: true
env:
  REGISTRY: docker.io
  REPOSITORY: tbaile/lupus-api
  TAG: ${{ github.ref_name }}
jobs:
  build-image:
    name: Build ${{ matrix.image }} image and push
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        image:
          - app
          - web
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: Create new buildx builder
        uses: docker/setup-buildx-action@v2

      - name: Generate tags
        uses: docker/metadata-action@v4
        id: meta
        with:
          bake-target: ${{ matrix.image }}-release
          images: |
            ${{ env.REGISTRY }}/${{ env.REPOSITORY }}-${{ matrix.image }}
          tags: |
            type=ref,event=branch,enable=${{ github.ref != format('refs/heads/{0}', 'master') }}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}},enable=${{ !startsWith(github.ref, 'refs/tags/v0.') }}

      - name: Login to registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.registry_username }}
          password: ${{ secrets.registry_password }}

      - name: Build ${{ matrix.image }}-release target
        uses: docker/bake-action@v2.3.0
        with:
          files: |
            ./docker-bake.hcl
            ${{ steps.meta.outputs.bake-file }}
          set: |
            *.platform=linux/arm64,linux/amd64
          targets: ${{ matrix.image }}-release
