name: Build
on:
  workflow_call:
    inputs:
      push:
        type: boolean
        required: false
        default: false
    secrets:
      dockerhub_username:
        required: false
      dockerhub_token:
        required: false

env:
  repository: tbaile/lupus-api

jobs:
  build-image:
    name: Build ${{ matrix.image }} image and push
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        image:
          - app
          - web
        arch:
          - amd64
          - arm64
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
      - name: Create new buildx builder
        uses: docker/setup-buildx-action@v2
      - name: Generate tags
        uses: docker/metadata-action@v4
        id: meta
        with:
          bake-target: ${{ matrix.image }}-release
          images: |
            ${{ env.repository }}-${{ matrix.image }}
          tags: |
            type=ref,event=branch,enable=${{ github.ref != format('refs/heads/{0}', 'master') }}
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}},enable=${{ !startsWith(github.ref, 'refs/tags/v0.') }}
          flavor: |
            latest=false
            suffix=-${{ matrix.arch }}
      - name: Generate cache-from tags
        uses: docker/metadata-action@v4
        id: meta-cache-from
        with:
          images: |
            ${{ env.repository }}-${{ matrix.image }}
          tags: |
            type=raw,value=develop
            type=ref,event=branch
            type=ref,event=pr
          flavor: |
            latest=false
            suffix=-cache-${{ matrix.arch }}
      - name: Generate cache-to tags
        uses: docker/metadata-action@v4
        id: meta-cache-to
        with:
          images: |
            ${{ env.repository }}-${{ matrix.image }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
          flavor: |
            latest=false
            suffix=-cache-${{ matrix.arch }}
      - name: Transform cache tags
        id: bake-cache
        run: |
          cache_from_file="$(mktemp)"
          jq '{ "target": { "testing": { "cache-from": ."target"."docker-metadata-action"."tags" | map_values("type=registry,ref=" + .) } } }' ${{ steps.meta-cache-from.outputs.bake-file }} > "$cache_from_file"
          echo "::set-output name=cache-from::$cache_from_file"
          cache_to_file="$(mktemp)"
          jq '{ "target": { "testing": { "cache-to": ."target"."docker-metadata-action"."tags" | map_values("type=registry,ref=" + . + ",mode=max") } } }' ${{ steps.meta-cache-to.outputs.bake-file }} > "$cache_to_file"
          echo "::set-output name=cache-to::$cache_to_file"
      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.dockerhub_username }}
          password: ${{ secrets.dockerhub_token }}
      - uses: docker/bake-action@v2.2.0
        with:
          targets: ${{ matrix.image }}-release
          set: |
            *.platform=linux/${{ matrix.arch }}
          files: |
            ./docker-bake.hcl
            ${{ steps.meta.outputs.bake-file }}
            ${{ steps.bake-cache.outputs.cache-from }}
            ${{ steps.bake-cache.outputs.cache-to }}
          push: ${{ inputs.push }}
