name: CI
on:
  push:
    branches:
      - master
      - develop
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [ app, web ]
        arch: [ amd64, arm64 ]
        include:
          - image: app
            dockerfile: php
          - image: web
            dockerfile: nginx
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          tags: tbaile/lupus-${{ matrix.image }}-${{ matrix.arch }}
          platforms: linux/${{ matrix.arch }}
          file: docker/${{ matrix.dockerfile }}/Dockerfile
          cache-from: type=registry,ref=tbaile/lupus-${{ matrix.image }}:cache-${{ matrix.arch }}
          cache-to: type=registry,ref=tbaile/lupus-${{ matrix.image }}:cache-${{ matrix.arch }},mode=max
          context: .
          outputs: type=docker,dest=/tmp/lupus-${{ matrix.image }}-${{ matrix.arch }}.tar
      - uses: actions/upload-artifact@v2
        with:
          name: lupus-${{ matrix.image }}-${{ matrix.arch }}
          path: /tmp/lupus-${{ matrix.image }}-${{ matrix.arch }}.tar
  push:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        image: [ app, web ]
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/metadata-action@v3
        id: meta
        with:
          images: tbaile/lupus-${{ matrix.image }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}},enable=${{ !startsWith(github.ref, 'refs/tags/v0.') }}
            type=ref,event=branch
      - uses: actions/download-artifact@v3
        with:
          name: lupus-${{ matrix.image }}-arm64
          path: /tmp
      - uses: actions/download-artifact@v3
        with:
          name: lupus-${{ matrix.image }}-amd64
          path: /tmp
      - run: |
          docker load --input /tmp/lupus-${{ matrix.image }}-arm64.tar
          docker load --input /tmp/lupus-${{ matrix.image }}-amd64.tar
      - uses: docker/build-push-action@v2
        with:
          tags: ${{ steps.meta.outputs.tags }}
          platforms: linux/arm64, linux/amd64
          file: docker/${{ matrix.dockerfile }}/Dockerfile
          context: .
          push: true
