name: CI
on:
  push:
    branches-ignore:
      - "renovate/**"
    paths-ignore:
      - '.idea/**'
      - 'containers/.env.example'
      - 'containers/docker-compose.yml'
      - '.editorconfg'
      - '.env.example'
      - '.gitattributes'
      - '.gitignore'
      - '.nvmrc'
      - '.styleci.yml'
      - 'docker-compose.yml'
      - 'phpstan.neon.dist'
      - 'README.md'
      - 'renovate.json'
jobs:
  test-app-image:
    uses: ./.github/workflows/test.yml
  build-and-push-images:
    uses: ./.github/workflows/build.yml
    needs:
      - test-app-image
    secrets: inherit
