name: CI
on:
  push:
    branches:
      - develop
    paths-ignore:
      - '.idea/**'
      - '.editorconfg'
      - '.env.example'
      - '.gitattributes'
      - '.gitignore'
      - '.lando.yml'
      - '.nvmrc'
      - '.styleci.yml'
      - 'renovate.json'
      - 'README.md'
      - 'phpstan.neon.dist'
env:
  REPOSITORY: tbaile/lupus-api
jobs:
  test-app-image:
    uses: ./.github/workflows/test.yml
  build-and-push-images:
    uses: ./.github/workflows/build.yml
    needs:
      - test-app-image
    secrets: inherit
