name: CI
on:
  push:
    branches-ignore:
      - "renovate/**"
env:
  REPOSITORY: tbaile/lupus-api
jobs:
  test-app-image:
    uses: ./.github/workflows/test.yml
  build-and-push-images:
    uses: ./.github/workflows/build.yml
    needs:
      - test-app-image
    secrets: inherit
    with:
      push: true
