name: Development CI
on:
  push:
    branches:
      - develop
  schedule:
    - cron: '0 2 * * 1'
jobs:
  test-app:
    uses: ./.github/workflows/test.yml
  build-and-push:
    runs-on: ubuntu-latest
    needs:
      - test-app
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build images and push
        run: ./build.sh
