name: CI
on:
  push:
    branches:
      - master
      - develop
  workflow_dispatch:
jobs:
  build-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/metadata-action@v3
        id: meta-app
        with:
          images: tbaile/lupus-app
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}},enable=${{ !startsWith(github.ref, 'refs/tags/v0.') }}
            type=ref,event=branch
      - name: Build app images
        uses: docker/build-push-action@v2
        with:
          tags: ${{ steps.meta-app.outputs.tags }}
          platforms: linux/arm64,linux/amd64
          file: docker/php/Dockerfile
          cache-from: type=registry,ref=tbaile/lupus-app:cache
          cache-to: type=registry,ref=tbaile/lupus-app:cache,mode=max
          push: true
          context: .
      - uses: docker/metadata-action@v3
        id: meta-web
        with:
          images: tbaile/lupus-web
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}},enable=${{ !startsWith(github.ref, 'refs/tags/v0.') }}
            type=ref,event=branch
      - name: Build app images
        uses: docker/build-push-action@v2
        with:
          tags: ${{ steps.meta-web.outputs.tags }}
          platforms: linux/arm64,linux/amd64
          file: docker/nginx/Dockerfile
          cache-from: type=registry,ref=tbaile/lupus-web:cache
          cache-to: type=registry,ref=tbaile/lupus-web:cache,mode=max
          push: true
          context: .
