name: CI
on:
  push:
    branches:
      - master
      - develop
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [ app, web ]
        arch: [ amd64, arm64 ]
        include:
          - image: app
            dockerfile: php
          - image: web
            dockerfile: nginx
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/metadata-action@v4
        id: meta
        with:
          images: tbaile/lupus-${{ matrix.image }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}},enable=${{ !startsWith(github.ref, 'refs/tags/v0.') }}
            type=ref,event=branch
          flavor: |
            suffix=-${{ matrix.arch }},onlatest=true
      - uses: docker/build-push-action@v3
        with:
          file: docker/${{ matrix.dockerfile }}/Dockerfile.${{ matrix.arch }}
          platforms: linux/${{ matrix.arch }}
          tags: ${{ steps.meta.outputs.tags }}
          push: true
          context: .
          cache-from: type=registry,ref=tbaile/lupus-${{ matrix.image }}:cache-${{ matrix.arch }}
          cache-to: type=registry,ref=tbaile/lupus-${{ matrix.image }}:cache-${{ matrix.arch }}
