name: CI
on:
  push:
    branches:
      - master
      - develop
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [ app, web ]
        include:
          - image: app
            dockerfile: php
          - image: web
            dockerfile: nginx
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/metadata-action@v4
        id: meta
        with:
          images: tbaile/lupus-${{ matrix.image }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}},enable=${{ !startsWith(github.ref, 'refs/tags/v0.') }}
            type=ref,event=branch
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - uses: docker/build-push-action@v3
        with:
          file: docker/${{ matrix.dockerfile }}/Dockerfile
          platforms: linux/arm64, linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          push: true
          context: .
          cache-from: type=registry,ref=tbaile/lupus-${{ matrix.image }}:${{ steps.extract_branch.outputs.branch }}
          cache-to: type=inline
