name: Development CI
on:
  push:
    branches:
      - develop
env:
  REPOSITORY: tbaile/lupus-api
jobs:
  test-app-image:
    uses: ./.github/workflows/test.yml
  build-and-push-images:
    runs-on: ubuntu-latest
    needs:
      - test-app-image
    strategy:
      matrix:
        image:
          - app
          - web
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/metadata-action@v4
        id: meta
        with:
          images: |
            ${{ env.REPOSITORY }}-${{ matrix.image }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}},enable=${{ !startsWith(github.ref, 'refs/tags/v0.') }}
      - uses: docker/bake-action@v2.2.0
        with:
          targets: ${{ matrix.image }}-release
          set: |
            *.platform=linux/arm64,linux/amd64
            *.cache-from=type=registry,ref=${{ env.REPOSITORY }}-${{ matrix.image }}:develop
            *.cache-from=type=registry,ref=${{ join(fromJSON(steps.meta.outputs.json).tags, ' *.cache-from=type=registry,ref=') }}
          files: |
            ./docker-bake.hcl
            ${{ steps.meta.outputs.bake-file }}
          push: true
