name: CI
on:
  push:
  workflow_dispatch:
jobs:
  build-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/metadata-action@v3
        id: meta-app
        with:
          images: tbaile/lupus-app
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}},enable=${{ !startsWith(github.ref, 'refs/tags/v0.') }}
            type=ref,event=branch
      - name: Build and push app images
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/php/Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta-app.outputs.tags }}
          push: true
          cache-from: type=registry,ref=tbaile/lupus-app:buildcache
          cache-to: type=registry,ref=tbaile/lupus-app:buildcache,mode=max
      - uses: docker/metadata-action@v3
        id: meta-web
        with:
          images: tbaile/lupus-web
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}},enable=${{ !startsWith(github.ref, 'refs/tags/v0.') }}
            type=ref,event=branch
      - name: Build and push web images
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/nginx/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta-web.outputs.tags }}
          cache-from: type=registry,ref=tbaile/lupus-web:buildcache
          cache-to: type=registry,ref=tbaile/lupus-web:buildcache,mode=max
