name: Test-CI
on:
  push:
    branches:
      - bugfix/fix-multiplatform-cache
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.export_tags.outputs.tags }}
    strategy:
      matrix:
        image: [ app, web ]
        arch: [ amd64, arm64 ]
        include:
          - image: app
            folder: php
          - image: web
            folder: nginx
    steps:
      - uses: actions/checkout@v3
      - uses: docker/metadata-action@v4
        id: meta
        with:
          images: tbaile/lupus-${{ matrix.image }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}},enable=${{ !startsWith(github.ref, 'refs/tags/v0.') }}
            type=ref,event=branch,
            type=sha
          flavor: |
            suffix=-${{ matrix.arch }},onlatest=true
      - id: export_tags
        run: echo "::set-output name=matrix::${{ steps.meta.outputs.tags }}"
  manifest:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - run: |
          echo ${{ needs.build.outputs.tags }}
