name: Test
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  test-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - name: Build testing images
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/php/Dockerfile
          platforms: linux/arm64,linux/amd64
          target: testing
          cache-from: type=registry,ref=tbaile/lupus-app:buildcache
