name: Testing
on:
  pull_request:
  workflow_call:
env:
  repository: tbaile/lupus-api
jobs:
  test-app-image:
    name: Test app image
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        arch:
          - amd64
          - arm64
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/metadata-action@v4
        id: meta-cache
        with:
          images: |
            ${{ env.repository }}-app
          tags: |
            type=raw,value=develop
            type=ref,event=branch
            type=ref,event=pr
          flavor: |
            latest=false
            suffix=-cache-${{ matrix.arch }}
      - id: bake-cache-from
        run: |
          tmpfile="$(mktemp)"
          jq '{ "target": { "testing": { "cache-from": ."target"."docker-metadata-action"."tags" | map_values("type=registry,ref=" + .) } } }' ${{ steps.meta-cache.outputs.bake-file }} > "$tmpfile"
          echo "::set-output name=file::$tmpfile"
      - uses: docker/bake-action@v2.2.0
        with:
          files: |
            ./docker-bake.hcl
            ${{ steps.bake-cache-from.outputs.file }}
          targets: testing
          set: |
            *.platform=linux/${{ matrix.arch }}
