name: Tests
on: pull_request
jobs:
  test-images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [ app, web ]
        arch: [ amd64, arm64 ]
        include:
          - image: app
            dockerfile: php
          - image: web
            dockerfile: nginx
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v3
        with:
          file: docker/${{ matrix.dockerfile }}/Dockerfile
          platforms: linux/${{ matrix.arch }}
          target: testing
          context: .
          cache-from: type=registry,ref=tbaile/lupus-${{ matrix.image }}:${{ github.base_ref }}-cache-${{ matrix.arch }}
