name: Tests
on: pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [ app, web ]
        include:
          - image: app
            dockerfile: php
          - image: web
            dockerfile: nginx
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v3
        with:
          file: docker/${{ matrix.dockerfile }}/Dockerfile
          platforms: linux/arm64, linux/amd64
          context: .
          cache-from: type=registry,ref=tbaile/lupus-${{ matrix.image }}:$GITHUB_BASE_REF
