name: Tests
on:
  pull_request:
  workflow_call:
jobs:
  test-images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [ amd64, arm64 ]
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v3
        with:
          file: docker/php/Dockerfile
          platforms: linux/${{ matrix.arch }}
          target: testing
          context: .
          cache-from: type=registry,ref=tbaile/lupus-app:${{ github.base_ref }}-cache-${{ matrix.arch }}
